# Generated by Django 2.2.7 on 2021-02-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
    ]
