# Generated by Django 2.2.7 on 2021-02-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210209_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='usermodified',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usermodified',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='usermodified',
        ),
    ]
