# Generated by Django 2.2.7 on 2021-02-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210209_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='breathingfrequency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Frecuencia respiratoria'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='examinationid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Examination', verbose_name='Examen id'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='heartfrequency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Frecuencia cardiaca'),
        ),
    ]
