# Generated by Django 2.2.7 on 2021-01-29 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(verbose_name='Observaciones')),
                ('image', models.ImageField(upload_to='bdd', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('maxturn', models.IntegerField(verbose_name='Turnos maximos')),
                ('entrytime', models.TimeField(verbose_name='Hora de entrada')),
                ('departuretime', models.TimeField(verbose_name='Hora de salida')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('gender', models.CharField(max_length=50, verbose_name='Genero')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('dni', models.CharField(max_length=255, verbose_name='Identificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('usermodified', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ultimo Usuario modificador')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField(verbose_name='Pregunta de seguridad')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('company', models.CharField(max_length=255, verbose_name='Compañia')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('gender', models.CharField(max_length=50, verbose_name='Genero')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('dni', models.CharField(max_length=255, verbose_name='Identificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('image', models.ImageField(upload_to='bdd', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('usertipe', models.CharField(max_length=255, verbose_name='Tipo de usuario')),
                ('answer', models.CharField(max_length=255, verbose_name='Respuesta de seguridad')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Question', verbose_name='Seguridad')),
                ('usermodified', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ultimo Usuario modificador')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('symptoms', models.TextField(verbose_name='Sintomas')),
                ('medication', models.TextField(verbose_name='Medicacion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('dateappointment', models.DateTimeField(verbose_name='Fecha de la cita')),
                ('active', models.BooleanField(default=True)),
                ('medicid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Medic', verbose_name='Medico id')),
                ('patientid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Patient', verbose_name='Paciente id')),
                ('usermodified', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ultimo Usuario modificador')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agenda',
                'ordering': ['active'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('feeding', models.TextField(verbose_name='Alimentacion')),
                ('diuresis', models.TextField(verbose_name='Diuresis')),
                ('catharsis', models.TextField(verbose_name='Catarsis')),
                ('diseases', models.TextField(verbose_name='Enfermedades')),
                ('hereditary', models.TextField(verbose_name='Enfermedades heredofamiliares')),
                ('menstrual', models.TextField(verbose_name='Menstruales')),
                ('sexual', models.TextField(verbose_name='Sexuales')),
                ('menarca', models.TextField(verbose_name='Menarca')),
                ('mac', models.TextField(verbose_name='Mac')),
                ('fun', models.TextField(verbose_name='Fun')),
                ('menopause', models.TextField(verbose_name='Menopausia')),
                ('papsmear', models.TextField(verbose_name='Papanicolao')),
                ('mammography', models.TextField(verbose_name='Mamografia')),
                ('feats', models.TextField(verbose_name='Gestas')),
                ('deliveries', models.TextField(verbose_name='Partos')),
                ('abortions', models.TextField(verbose_name='Abortos')),
                ('caesarean', models.TextField(verbose_name='Cesareas')),
                ('others', models.TextField(verbose_name='Otros')),
                ('patientid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Patient', verbose_name='Paciente id')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo')),
                ('packagevalue', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor paquete')),
                ('unitvalue', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor unitario')),
                ('stocks', models.IntegerField(verbose_name='Stock')),
                ('duedate', models.DateField(verbose_name='Fecha de vencimiento')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('code', models.CharField(max_length=255, verbose_name='Codigo')),
                ('categoryid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Category', verbose_name='Categoria id')),
                ('supplierid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Supplier', verbose_name='Proveedor id')),
                ('usermodified', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ultimo Usuario modificador')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Medic', verbose_name='Medico id')),
                ('specialtyid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Specialty', verbose_name='Especialidad id')),
            ],
            options={
                'verbose_name': 'Medico especialidad',
                'verbose_name_plural': 'Medico especialidad',
            },
        ),
        migrations.AddField(
            model_name='medic',
            name='iduser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.User', verbose_name='Usuario id'),
        ),
        migrations.AddField(
            model_name='medic',
            name='usermodified',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ultimo Usuario modificador'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateattention', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de atencion')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Indice de masa corporal')),
                ('exploration', models.TextField(verbose_name='Exploracion')),
                ('sickness', models.TextField(verbose_name='Enfermedad actual')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura')),
                ('heartfrequency', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Frecuencia cardiaca')),
                ('breathingfrequency', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Frecuencia respiratoria')),
                ('diagnosis', models.TextField(verbose_name='Diagnostico')),
                ('medication', models.TextField(verbose_name='Medicacion')),
                ('recommendations', models.TextField(verbose_name='Recomendaciones')),
                ('examinationid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Examination', verbose_name='Examen id')),
                ('scheduleid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Schedule', verbose_name='Agenda di')),
            ],
        ),
    ]
