# Generated by Django 2.2.7 on 2021-02-05 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField(verbose_name='Pregunta de seguridad')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellido')),
                ('gender', models.CharField(max_length=50, verbose_name='Genero')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('dni', models.CharField(max_length=255, verbose_name='Identificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('image', models.ImageField(upload_to='bdd', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('active', models.BooleanField(default=True)),
                ('usertipe', models.CharField(max_length=255, verbose_name='Tipo de usuario')),
                ('answer', models.CharField(max_length=255, verbose_name='Respuesta de seguridad')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Question', verbose_name='Seguridad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['created'],
            },
        ),
    ]
